/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MinhasVendasRouteImport } from './routes/minhas-vendas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as IndexRouteImport } from './routes/index'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasVendasRoute = MinhasVendasRouteImport.update({
  id: '/minhas-vendas',
  path: '/minhas-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/minhas-vendas': typeof MinhasVendasRoute
  '/painel': typeof PainelRoute
  '/pdv': typeof PdvRoute
  '/perfil': typeof PerfilRoute
  '/scan': typeof ScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/minhas-vendas': typeof MinhasVendasRoute
  '/painel': typeof PainelRoute
  '/pdv': typeof PdvRoute
  '/perfil': typeof PerfilRoute
  '/scan': typeof ScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/minhas-vendas': typeof MinhasVendasRoute
  '/painel': typeof PainelRoute
  '/pdv': typeof PdvRoute
  '/perfil': typeof PerfilRoute
  '/scan': typeof ScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipe'
    | '/login'
    | '/minhas-vendas'
    | '/painel'
    | '/pdv'
    | '/perfil'
    | '/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipe'
    | '/login'
    | '/minhas-vendas'
    | '/painel'
    | '/pdv'
    | '/perfil'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/equipe'
    | '/login'
    | '/minhas-vendas'
    | '/painel'
    | '/pdv'
    | '/perfil'
    | '/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipeRoute: typeof EquipeRoute
  LoginRoute: typeof LoginRoute
  MinhasVendasRoute: typeof MinhasVendasRoute
  PainelRoute: typeof PainelRoute
  PdvRoute: typeof PdvRoute
  PerfilRoute: typeof PerfilRoute
  ScanRoute: typeof ScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-vendas': {
      id: '/minhas-vendas'
      path: '/minhas-vendas'
      fullPath: '/minhas-vendas'
      preLoaderRoute: typeof MinhasVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipeRoute: EquipeRoute,
  LoginRoute: LoginRoute,
  MinhasVendasRoute: MinhasVendasRoute,
  PainelRoute: PainelRoute,
  PdvRoute: PdvRoute,
  PerfilRoute: PerfilRoute,
  ScanRoute: ScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
